version: "3"
services:
  backend:
    build:
      context: api
  frontend:
    build:
      context: social-network
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

