--Create the chat table
CREATE TABLE IF NOT EXISTS chat (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
  message TEXT NOT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP
);